name: Secrets-Test
on:
  push:
    branches: [secrets]
jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ secrets.MY_SECRET }}
    steps:
      - run: echo "Secret consumed"

  Lint:
    needs: Setup
    if: needs.Setup.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.Setup.outputs.node_version }}
      - run: npm ci
      - run: npm run lint
